ERROR - 2022-12-21 02:16:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:16:30 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:18 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:18 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:20 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:20 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:29 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:29 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:30 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:30 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:46 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:46 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:52 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:52 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:17:58 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:17:58 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:18:12 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:18:12 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:20:35 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:20:35 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-21 02:20:45 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'baseattackforce', 3306, '', 0)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseattackforce' in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 E:\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 E:\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\BaseAttackForceScrapy\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('E:\\BaseAttackFo...')
#12 {main}
CRITICAL - 2022-12-21 02:20:45 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseattackforce'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 02:46:28 --> Undefined index: Rank
in APPPATH\Views\alliance\overview.php on line 39.
 1 APPPATH\Views\alliance\overview.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: Rank', 'APPPATH\\Views\\alliance\\overview.php', 39, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\alliance\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('alliance/overview', [], true)
 5 APPPATH\Controllers\Alliance.php(30): view('alliance/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Alliance->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alliance))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 12:57:33 --> syntax error, unexpected 'endforeach' (T_ENDFOREACH)
in APPPATH\Views\alliance\overview.php on line 56.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('alliance/overview', [], true)
 3 APPPATH\Controllers\Alliance.php(30): view('alliance/overview')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Alliance->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alliance))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:01 --> Undefined variable: data
in APPPATH\Controllers\Maps.php on line 9.
 1 APPPATH\Controllers\Maps.php(9): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: data', 'APPPATH\\Controllers\\Maps.php', 9, [])
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:24 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:55 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:57 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:58 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:58 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:58 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:10:59 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:00 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:01 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:01 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:01 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:01 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:02 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:02 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:02 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:02 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:03 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:03 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:03 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:03 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:03 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:04 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:04 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 13:11:04 --> Undefined variable: title
in APPPATH\Views\maps\overview.php on line 6.
 1 APPPATH\Views\maps\overview.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\maps\\overview.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\maps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('maps/overview', [], true)
 5 APPPATH\Controllers\Maps.php(10): view('maps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Maps->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Maps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 14:16:51 --> Undefined variable: battles
in APPPATH\Views\profile\overview.php on line 976.
 1 APPPATH\Views\profile\overview.php(976): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: battles', 'APPPATH\\Views\\profile\\overview.php', 976, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\profile\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 5 APPPATH\Controllers\Profile.php(30): view('profile/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 14:23:53 --> Call to undefined method App\Controllers\Battle::getUserBattles()
in APPPATH\Controllers\Profile.php on line 28.
 1 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 2 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 14:24:54 --> Undefined variable: battles
in APPPATH\Views\profile\overview.php on line 976.
 1 APPPATH\Views\profile\overview.php(976): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: battles', 'APPPATH\\Views\\profile\\overview.php', 976, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\profile\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 5 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 14:41:27 --> Undefined variable: user
in APPPATH\Views\profile\overview.php on line 23.
 1 APPPATH\Views\profile\overview.php(23): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\profile\\overview.php', 23, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\profile\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 5 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 17:16:11 --> Too few arguments to function App\Controllers\BattleMaps::index(), 0 passed in E:\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php on line 927 and exactly 1 expected
in APPPATH\Controllers\BattleMaps.php on line 7.
 1 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\BattleMaps->index()
 2 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BattleMaps))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 17:16:39 --> Undefined variable: data
in APPPATH\Views\battlemaps\overview.php on line 28.
 1 APPPATH\Views\battlemaps\overview.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: data', 'APPPATH\\Views\\battlemaps\\overview.php', 28, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\battlemaps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('battlemaps/overview', [], true)
 5 APPPATH\Controllers\BattleMaps.php(11): view('battlemaps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\BattleMaps->index('11')
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BattleMaps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 17:20:10 --> Undefined variable: i
in APPPATH\Views\battlemaps\overview.php on line 12.
 1 APPPATH\Views\battlemaps\overview.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: i', 'APPPATH\\Views\\battlemaps\\overview.php', 12, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\battlemaps\\overview.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('battlemaps/overview', [], true)
 5 APPPATH\Controllers\BattleMaps.php(11): view('battlemaps/overview')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\BattleMaps->index('86')
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BattleMaps))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 20:05:32 --> Call to undefined function dump()
in APPPATH\Views\profile\overview.php on line 22.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 4 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 20:05:35 --> Call to undefined function dump()
in APPPATH\Views\profile\overview.php on line 22.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 4 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 20:05:35 --> Call to undefined function dump()
in APPPATH\Views\profile\overview.php on line 22.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 4 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 20:05:35 --> Call to undefined function dump()
in APPPATH\Views\profile\overview.php on line 22.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 4 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-21 20:05:47 --> Call to undefined function dump()
in APPPATH\Views\profile\overview.php on line 22.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('profile/overview', [], true)
 4 APPPATH\Controllers\Profile.php(33): view('profile/overview')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
