ERROR - 2022-12-28 03:48:48 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://151.106...', 'nouahsar_Amjad2...', 'Rook700Jean956', 'nouahsar_baseat...', 3306, '', 0)
#2 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\BaseAttackForceScrapy\app\Models\UserModel.php(36): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\BaseAttackForceScrapy\app\Controllers\Profile.php(28): App\Models\UserModel->getUserById(NULL)
#9 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Profile->index()
#10 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
#11 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\BaseAttackForceScrapy\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://151.106...', 'nouahsar_Amjad2...', 'Rook700Jean956', 'nouahsar_baseat...', 3306, '', 0)
#1 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\BaseAttackForceScrapy\app\Models\UserModel.php(36): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\BaseAttackForceScrapy\app\Controllers\Profile.php(28): App\Models\UserModel->getUserById(NULL)
#8 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Profile->index()
#9 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
#10 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\BaseAttackForceScrapy\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\BaseAttackForceScrapy\app\Models\UserModel.php(36): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\BaseAttackForceScrapy\app\Controllers\Profile.php(28): App\Models\UserModel->getUserById(NULL)
#7 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Profile->index()
#8 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
#9 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\BaseAttackForceScrapy\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-12-28 03:48:48 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for https failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `id` IS NULL
 LIMIT 1', [], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(36): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Profile.php(28): App\Models\UserModel->getUserById(null)
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Profile->index()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-28 03:50:18 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://151.106...', 'nouahsar_Amjad2...', 'Rook700Jean956', 'nouahsar_baseat...', 3306, '', 0)
#2 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#9 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#10 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\BaseAttackForceScrapy\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://151.106...', 'nouahsar_Amjad2...', 'Rook700Jean956', 'nouahsar_baseat...', 3306, '', 0)
#1 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#8 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#9 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\BaseAttackForceScrapy\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\BaseAttackForceScrapy\app\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\BaseAttackForceScrapy\app\Controllers\Auth.php(40): App\Models\UserModel->auth(Array)
#7 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\BaseAttackForceScrapy\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\BaseAttackForceScrapy\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-12-28 03:50:18 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for https failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Auth.php(40): App\Models\UserModel->auth([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
